### PR TITLE
tech(Blizzard API): add Blizzard API and Auth for future use

### PR DESCRIPTION
**Pull request by BernardJeremy**
**Summary**

This patch add a way to call the official Blizzard API (https://dev.battle.net/io-docs) for future use.

**Important notes**

Blizzard's API as it is implemented in this patch **needs two keys to works**, both of them have to be in the proper config file. Those keys are issued by Blizzard to enforce the oauth authentification (more details [here](https://dev.battle.net/docs/read/oauth). See **New configuration values** part for specifics.

Currently, **the access token generated by the two keys is kept for 24 hours**. That way, the server will only request a new access token once per day. We could decide to request a new one with each API request to be extremely safe about the token viability (I don't advise that at all). We could also use the real expiration time : 30 days, even if I consider quite unsafe to do so, considering that if the token is revoked, the implementation won't work until the exact 30 days time. Feel free to comment about that call :) 

**Tasks**

- [x] Follow existing code architecture and practice.
- [x] Functional test.

**New configuration values** 
- _client_id_: API account specific key (found [here](https://dev.battle.net/apps/mykeys) once logged).
- _client_secret_: Application specific key (found [here](https://dev.battle.net/apps/mykeys) once logged).
- _grant_type_: Authentification type, we are using _client_credentials_ for now.
- _token_url_: URL to retrieve the access_token from Blizzard's oauth service.

### CODE REVIEW

**Comment by WFrancois** [comment]
Hey !

Nice, work. Yeah, 1 day should be good enough.

Wondering though, not sure if it's the optimal way, but would it be possible to increase the cache token live, then when we're doing a request using the access token, if it fails because of authentification, we regenerate the token and retry again ?

Will try to ask what the best method is to handle that :)

**Comment by BernardJeremy** [comment]
Indeed, it's something we could do ! Nevertheless, I wonder if we could just trust the Blizzard's expiration time (about 30 days) which is returned with the token itself... Interesting subject !

**Comment by WFrancois** [comment]
I think we could trust Blizzard's expiration time, and I don't think the token can be revoked.

I was doubting because twitch api revoked the token when we asked for another one. It's not the case with blizzard, so I don't see why it should be revoked.
And if I have an issue, I just have to restart the bot :p

**Comment by BernardJeremy** [comment]
I agree with you, we should trust Blizzard on that one 😛 
I amended the patch accordingly, now using the oauth API expiration time.

**Review by WFrancois — APPROVED** [review]
Alright, nice addition, will be useful ! :p

**Pull request merged**
